version: '3.8'

services:
  musicbot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    env_file:
      - .env
    volumes:
      - ./bot.py:/app/bot.py
